### ISSUE TITLE
Can BlockingWaitStrategy and SleepingWaitStrategy be integrated?

### ISSUE THREAD

**Issue by ulnit** [nicholassm/disruptor-rs#1]
When there is no data inflow, the busyspin wait strategy consumes all the CPU.

**Comment by nicholassm** [comment]
They definitely can.
However, if you want to conserve CPU resources, why not use the excellent [crossbeam](https://crates.io/crates/crossbeam) library instead?

Currently, it would be easiest to integrate the `SleepingWaitStrategy`. The `BlockingWaitStrategy` requires a bit more rework of the internals. I'll add the `SleepingWaitStrategy` to the roadmap.

Kind regards
Nicholas

**Comment by ulnit** [comment]
> They definitely can. However, if you want to conserve CPU resources, why not use the excellent [crossbeam](https://crates.io/crates/crossbeam) library instead?
> 
> Currently, it would be easiest to integrate the `SleepingWaitStrategy`. The `BlockingWaitStrategy` requires a bit more rework of the internals. I'll add the `SleepingWaitStrategy` to the roadmap.
> 
> Kind regards Nicholas

Sure, thank you . I will try using the crossbeam library first.
