### ISSUE TITLE
How to build a pipeline workflow in the current structure?

### ISSUE THREAD

**Issue by lluckydog** [nicholassm/disruptor-rs#10]
Hi, dear author! I'm impressed by the good performance of this repo. However, I get a little confused when I am building my own work. Here is the problem: I want to build a pipeline workflow with disruptor. In the pipeline, a thread will work as both producer and consumer to the job. Is there any good idea how to build this kind of work? Thank you very much!

Yours,
danny

**Comment by nicholassm** [comment]
Hi Danny,

Yes, absolutely!
Check out the tests in `lib.rs` - there's an example of a pipeline where a consumer is also a producer.
Note, that the pipeline has to be constructed in reverse starting with the end consumer.

Kind regards,
    Nicholas
