### ISSUE TITLE
`Shared::pined_at_core` should probably be named `Shared::pinned_at_core` or something similar

### ISSUE THREAD

**Issue by superwhiskers** [nicholassm/disruptor-rs#14]
there's not much else to add here. it's just a minor spelling mistake that i noticed. this is ostensibly a breaking change though, so it may not be worth fixing without multiple other breaking changes being made at the same time to avoid needlessly incrementing the major version number

**Comment by nicholassm** [comment]
Damnit - that's what I get from not being a native English speaker... :-)
Thanks for noticing.
Version numbers are cheap and I prefer all client code bases to not have spelling mistakes so I think it's worth a major version. Plus it will be easy to upgrade. :-)

**Comment by superwhiskers** [comment]
no problem. thanks for the quick response
