### ISSUE TITLE
How to move Producer?

### ISSUE THREAD

**Issue by aasimovv** [nicholassm/disruptor-rs#3]
Hi,

I would like to move the producer to a function, but the producer crate is private, how can I specify the type for 

MultiProducer<EventDisrupt, SingleConsumerBarrier> 

Is it even possible ?

**Comment by nicholassm** [comment]
Hi,

That's absolutely not the intention!
If the privacy is too restrictive, I'll loosen it.

Stay tuned, I'm traveling the next few days so won't be able to do coding
while I'm away.

Kind regards
    Nicholas

ons. 24. apr. 2024 22.18 skrev aasimovv ***@***.***>:

**Comment by aasimovv** [comment]
Hey, I've made a PR for this: https://github.com/nicholassm/disruptor-rs/pull/5

**Comment by nicholassm** [comment]
Hi Aasimovv,

Many thanks for the PR.
I'll look at it when I'm back at my laptop.

Kind regards
     Nicholas

fre. 26. apr. 2024 22.36 skrev aasimovv ***@***.***>:

**Comment by nicholassm** [comment]
You can use version 1.1.0 now with the re-exports.
Thanks.
